jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # check is correct version

      - name: Simulate Install dependencies
        run: echo "Dependencies simulated successfully!"

      - name: Simulate Run tests
        run: echo "Tests simulated successfully!"